# add by martinec
# based on:
# https://github.com/mapbox/protozero/blob/master/.travis.yml
# https://github.com/dftlibs/xcfun/blob/master/.travis.yml
# https://github.com/clMathLibraries/clBLAS/blob/master/.travis.yml
# https://github.com/Automattic/_s/blob/master/.travis.yml

# language: instructs travis what compilers && environment to set up in build matrix
language: cpp

# sudo: false instructs travis to build our project in a docker VM (faster)
sudo: required

# only available on private builds
cache:
 - apt

# Save common build configurations as shortcuts, so we can reference them later.
addons_shortcuts:
  addons_clang35: &clang35
    apt:
      sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5' ]
      packages: [ 'clang-3.5', 'cmake', 'cppcheck' ]
  addons_gcc48: &gcc48
    apt:
      sources: [ 'ubuntu-toolchain-r-test' ]
      packages: [ 'g++-4.8', 'gcc-4.8', 'cmake', 'cppcheck' ]

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: "clang"
      env: CXX=clang++-3.5 CC=clang
      addons: *clang35
    - os: linux
      dist: trusty
      compiler: "gcc"
      env: CXX=g++-4.8 CC=gcc
      addons: *gcc48
  #exclude:
    #- os: linux    
      #compiler: gcc
    #- os: clang    
      #compiler: clang 
      
#notifications:
  #email:
    #recipients:
      #- unitex-devel@univ-mlv.fr
    #on_success: change
    #on_failure: always
  #slack:
    #secure: UvrwS8TG+pXKsgJGP2OouOpLGcf0ZsbgZzdUsGbfW+5WFl5/AZW6wxJg60jpHMgOcwoX74vvb0mpBOFNuV5Zck6ISBa3W4qSQeqmIJ+v7pzNNC1rEUGhictKX1Jo1MCRMN7Q0B+V5ZiWU6yVBljTo2PvhkeF27ethPyQpTyV3U88y45iX5mQP8+ZUaHdpBhxzN3x+9XzUTAV/ugrCrTJs315hXVhXpyaDFk4hE1nsRVCXyazX4JkHaCPau3hpdrtTF8Xpadu/u1MzaDFBZAgGUSvcV9rkJ6JpgyLlBFT/yyY7uqJ245LM4nfp/+SgS6p3eEEkbck+2x+dtS7OMSVGyZ4IwsWYU7TdAAnvy1u73TXCKkeYx6MbUEdI4wCJu5KUv8fJ4DJWsOc4RPCd36FGyNo8CfzJ4G8qaSaQr1U2xbPGPAebvrnEq2D/BgzY4/4BqHWBQCSctWCAfbehIPkjEy6JM+LDERJW85kTF5O4jUM0syyPmqWEsMfmZ6wQywQyGTA2BT4kTeDvS/ybiFqooOo03CF5K97S/ZdnOlXhFQLik3EVJwgq+k7rFkCXD/M63nwFdYV/59zBWy+xuFIUW8LDtZCssxZ9Wo8D3/PzPEb4nRECJ0Cmvs/tLKjw4ATrHrjKfxDyW55V6xFzg8DmZBhdQd+Puut8ZIoDRziGaI=

before_install:
 # https://github.com/travis-ci/docs-travis-ci-com/commit/fbca7ce4
 # - test -n $CC && unset CC
 # - test -n $CXX && unset CXX
 - git clone -b master --depth 1 https://github.com/UnitexGramLab/unitex-core && cd unitex-core && export UNITEX_CORE_GIT_REVISION=$(git describe --always HEAD) && mkdir bin && cd build && make DEBUG=yes UNITEXTOOLLOGGERONLY=yes && cd .. && export UNITEX_BIN="$PWD/bin/UnitexToolLogger" && cd ..
 - echo ${UNITEX_BIN} 
 - echo ${UNITEX_CORE_GIT_REVISION}

install:
  - "./shellcheck-install.sh"

script:
  - "./shellcheck-check.sh"
