# add by martinec
# =============================================================================
# based on:
# https://github.com/mapbox/protozero/blob/master/.travis.yml
# https://github.com/dftlibs/xcfun/blob/master/.travis.yml
# https://github.com/clMathLibraries/clBLAS/blob/master/.travis.yml
# https://github.com/Automattic/_s/blob/master/.travis.yml
# =============================================================================
# - To install the Travis CI command line client, which requires
#   Ruby 1.9.3 and RubyGems, type:
#   $ gem install travis --no-rdoc --no-ri
# - To run the command line lint tool, type:
#   $ travis lint
# =============================================================================

# language: instructs travis what compilers && environment to set up in build matrix
language: cpp

# sudo: false instructs Travis to build our project in a docker VM (faster)
sudo: required

# only available on private builds
cache:
 - apt

# Travis CI clones repositories to a depth of 50 commits
git:
  depth: 3 

# Save common build configurations as shortcuts, so we can reference them later.
addons_shortcuts:
  addons_clang35: &clang35
    apt:
      sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5' ]
      packages: [ 'clang-3.5', 'cmake', 'cppcheck', 'valgrind' ]
  addons_gcc48: &gcc48
    apt:
      sources: [ 'ubuntu-toolchain-r-test' ]
      packages: [ 'g++-4.8', 'gcc-4.8', 'cmake', 'cppcheck', 'valgrind' ]

matrix:
  # if a rows in the build matrix fails, set
  # the build to finish as soon as possible
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      compiler: "clang"
      env: CXX=clang++-3.5
      addons: *clang35
    - os: linux
      dist: trusty
      compiler: "gcc"
      env: CXX=g++-4.8
      addons: *gcc48
    - os: osx
      osx_image: xcode6.4
      compiler: clang
  allow_failures:
    - os: osx

notifications:
  email:
    recipients:
      - unitex-devel@univ-mlv.fr
    on_success: change
    on_failure: always
  slack:
    secure: UvrwS8TG+pXKsgJGP2OouOpLGcf0ZsbgZzdUsGbfW+5WFl5/AZW6wxJg60jpHMgOcwoX74vvb0mpBOFNuV5Zck6ISBa3W4qSQeqmIJ+v7pzNNC1rEUGhictKX1Jo1MCRMN7Q0B+V5ZiWU6yVBljTo2PvhkeF27ethPyQpTyV3U88y45iX5mQP8+ZUaHdpBhxzN3x+9XzUTAV/ugrCrTJs315hXVhXpyaDFk4hE1nsRVCXyazX4JkHaCPau3hpdrtTF8Xpadu/u1MzaDFBZAgGUSvcV9rkJ6JpgyLlBFT/yyY7uqJ245LM4nfp/+SgS6p3eEEkbck+2x+dtS7OMSVGyZ4IwsWYU7TdAAnvy1u73TXCKkeYx6MbUEdI4wCJu5KUv8fJ4DJWsOc4RPCd36FGyNo8CfzJ4G8qaSaQr1U2xbPGPAebvrnEq2D/BgzY4/4BqHWBQCSctWCAfbehIPkjEy6JM+LDERJW85kTF5O4jUM0syyPmqWEsMfmZ6wQywQyGTA2BT4kTeDvS/ybiFqooOo03CF5K97S/ZdnOlXhFQLik3EVJwgq+k7rFkCXD/M63nwFdYV/59zBWy+xuFIUW8LDtZCssxZ9Wo8D3/PzPEb4nRECJ0Cmvs/tLKjw4ATrHrjKfxDyW55V6xFzg8DmZBhdQd+Puut8ZIoDRziGaI=

before_install:
 # workaround for an issue related with the default export of the CC environment variable on Travis
 # https://github.com/travis-ci/travis-ci/issues/4682
 # https://github.com/travis-ci/docs-travis-ci-com/commit/fbca7ce4
 - test -n $CC && unset CC 
 - git clone -b master --depth 1 https://github.com/UnitexGramLab/unitex-core && cd unitex-core && export UNITEX_CORE_VERSION_GIT_COMMIT_HASH=$(git describe --always HEAD) && mkdir -p bin && cd build && make ADDITIONAL_CFLAG+=-DUNITEX_CORE_VERSION_GIT_COMMIT_HASH=${UNITEX_CORE_VERSION_GIT_COMMIT_HASH} DEBUG=yes UNITEXTOOLLOGGERONLY=yes && cd .. && export UNITEX_BIN="$PWD/bin/UnitexToolLogger" && cd ..
 - echo ${UNITEX_BIN} 
 - echo ${UNITEX_CORE_VERSION_GIT_COMMIT_HASH}

install:
  - "./shellcheck-install.sh"

# overwrite the default build step
script:
  - "./shellcheck-check.sh"
  - "./unitex-core-test.sh -w80 -p1"
