# add by martinec
# based on:
# https://github.com/mapbox/protozero/blob/master/.travis.yml
# https://github.com/dftlibs/xcfun/blob/master/.travis.yml
# https://github.com/clMathLibraries/clBLAS/blob/master/.travis.yml

# language: instructs travis what compilers && environment to set up in build matrix
language: cpp

# sudo: false instructs travis to build our project in a docker VM (faster)
sudo: false

# os: expands the build matrix to include multiple os's
os:
  - linux
  - osx

# compiler: expands the build matrix to include multiple compilers (per os)
compiler:
  - gcc
  - clang  

# Save common build configurations as shortcuts, so we can reference them later.
addons_shortcuts:
  addons_clang35: &clang35
    apt:
      sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-3.5' ]
      packages: [ 'clang-3.5', 'cmake' ]
  addons_clang38: &clang38
    apt:
      sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-trusty' ]
      packages: [ 'clang-3.8', 'cmake' ]
  addons_gcc49: &gcc47
    apt:
      sources: [ 'ubuntu-toolchain-r-test' ]
      packages: [ 'g++-4.7', 'gcc-4.7', 'cmake' ]
  addons_gcc49: &gcc48
    apt:
      sources: [ 'ubuntu-toolchain-r-test' ]
      packages: [ 'g++-4.8', 'gcc-4.8', 'cmake' ]
  addons_gcc49: &gcc49
    apt:
      sources: [ 'ubuntu-toolchain-r-test' ]
      packages: [ 'g++-4.9', 'gcc-4.9', 'cmake' ]
  addons_gcc49: &gcc5
    apt:
      sources: [ 'ubuntu-toolchain-r-test' ]
      packages: [ 'g++-5', 'gcc-5', 'cmake' ]

matrix:
  include:
    - os: osx
      osx_image: xcode6
      compiler: clang
    - os: osx
      osx_image: xcode7
      compiler: clang
    - os: linux
      dist: trusty
      compiler: "clang35"
      env: CXX=clang++-3.5
      addons: *clang35
    - os: linux
      dist: trusty
      compiler: "clang38"
      env: CXX=clang++-3.8
      addons: *clang38
    - os: linux
      dist: trusty
      compiler: "gcc47"
      env: CXX=g++-4.7
      addons: *gcc47
    - os: linux
      dist: trusty
      compiler: "gcc48"
      env: CXX=g++-4.8
      addons: *gcc48
    - os: linux
      dist: trusty
      compiler: "gcc49"
      env: CXX=g++-4.9 COVERAGE=gcov-4.9
      addons: *gcc49
    - os: linux
      dist: trusty
      compiler: "gcc5"
      env: CXX=g++-5 CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0"
      addons: *gcc5
    - os: linux
      dist: trusty
      compiler: "gcc5"
      env: CXX=g++-5 CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=1"
      addons: *gcc5

notifications:
  email:
    recipients:
      - unitex-devel@univ-mlv.fr
    on_success: change
    on_failure: always
  slack:
    secure: UvrwS8TG+pXKsgJGP2OouOpLGcf0ZsbgZzdUsGbfW+5WFl5/AZW6wxJg60jpHMgOcwoX74vvb0mpBOFNuV5Zck6ISBa3W4qSQeqmIJ+v7pzNNC1rEUGhictKX1Jo1MCRMN7Q0B+V5ZiWU6yVBljTo2PvhkeF27ethPyQpTyV3U88y45iX5mQP8+ZUaHdpBhxzN3x+9XzUTAV/ugrCrTJs315hXVhXpyaDFk4hE1nsRVCXyazX4JkHaCPau3hpdrtTF8Xpadu/u1MzaDFBZAgGUSvcV9rkJ6JpgyLlBFT/yyY7uqJ245LM4nfp/+SgS6p3eEEkbck+2x+dtS7OMSVGyZ4IwsWYU7TdAAnvy1u73TXCKkeYx6MbUEdI4wCJu5KUv8fJ4DJWsOc4RPCd36FGyNo8CfzJ4G8qaSaQr1U2xbPGPAebvrnEq2D/BgzY4/4BqHWBQCSctWCAfbehIPkjEy6JM+LDERJW85kTF5O4jUM0syyPmqWEsMfmZ6wQywQyGTA2BT4kTeDvS/ybiFqooOo03CF5K97S/ZdnOlXhFQLik3EVJwgq+k7rFkCXD/M63nwFdYV/59zBWy+xuFIUW8LDtZCssxZ9Wo8D3/PzPEb4nRECJ0Cmvs/tLKjw4ATrHrjKfxDyW55V6xFzg8DmZBhdQd+Puut8ZIoDRziGaI=

install:
- "./shellcheck-install.sh"

script:
- "./shellcheck-check.sh"
